substitutions:
  _CLUSTER_NAME: trillian-opensource-ci
  _MASTER_ZONE: us-central1-a
steps:
- id: build_hub
  name: gcr.io/cloud-builders/docker
  args:
  - build
  - --file=gossip/deployment/docker/hub/Dockerfile
  - --tag=gcr.io/${PROJECT_ID}/gossip-hub:${COMMIT_SHA}
  - .
  waitFor: ["-"]
- id: push_hub
  name: gcr.io/cloud-builders/docker
  args:
  - push
  - gcr.io/${PROJECT_ID}/gossip-hub:${COMMIT_SHA}
  waitFor:
  - build_hub
- id: tag_latest_hub
  name: gcr.io/cloud-builders/gcloud
  args:
  - container
  - images
  - add-tag
  - gcr.io/${PROJECT_ID}/gossip-hub:${COMMIT_SHA}
  - gcr.io/${PROJECT_ID}/gossip-hub:latest
  waitFor:
  - push_hub
- id: build_envsubst
  name: gcr.io/cloud-builders/docker
  args:
  - build
  - gossip/deployment/docker/envsubst
  - -t
  - envsubst
  waitFor: ["-"]
- id: envsubst_kubernetes_configs
  name: envsubst
  args:
  - gossip/deployment/kubernetes/gossip-hub-deployment.yaml
  - gossip/deployment/kubernetes/gossip-hub-service.yaml
  - gossip/deployment/kubernetes/gossip-hub-ingress.yaml
  env:
  - PROJECT_ID=${PROJECT_ID}
  - IMAGE_TAG=${COMMIT_SHA}
  waitFor:
  - build_envsubst
- id: update_kubernetes_configs
  name: gcr.io/cloud-builders/kubectl
  args:
  - apply
  - -f=gossip/deployment/kubernetes/gossip-hub-deployment.yaml
  - -f=gossip/deployment/kubernetes/gossip-hub-service.yaml
  - -f=gossip/deployment/kubernetes/gossip-hub-ingress.yaml
  env:
  - CLOUDSDK_COMPUTE_ZONE=${_MASTER_ZONE}
  - CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}
  waitFor:
  - envsubst_kubernetes_configs
  - push_hub
images:
- gcr.io/${PROJECT_ID}/gossip-hub:${COMMIT_SHA}
